config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  require 'sidekiq/web'

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  match '/widgets', to: 'widgets#index', via: [:get]

  match '/terms', to: 'welcome#terms', via: [:get]
  match '/privacy', to: 'welcome#privacy', via: [:get]
  match '/support', to: 'welcome#support', via: [:get]

  match '/canvas', to: 'canvas#index', via: [:get, :patch, :post]
  match '/canvas/edit', to: 'canvas#edit', via: [:get, :patch, :post]
  match '/giveaways/tab', to: 'giveaways#tab', via: [:get, :patch, :post]

  resources :likes, only: [:create]

  resources :facebook_pages, only: [:index, :show] do

    resources :giveaways do
      resources :entries, only: [:index, :create, :update]

      get :export_entries, on: :member
      get :active, on: :collection
      get :pending, on: :collection
      get :completed, on: :collection
      get :check_schedule, on: :collection
      get :clone, on: :member
      match :start, on: :member, via: [:get, :patch, :post]
      get :start_modal, on: :member
      get :end, on: :member
    end
  end

  match '/facebook_pages/:facebook_page_id/subscribe', to: 'subscriptions#create', as: 'facebook_page_subscribe', via: [:get, :post]

  match '/facebook_pages/:facebook_page_id/subscription_plans', to: 'subscription_plans#index', as: 'facebook_page_subscription_plans', via: [:get, :post]

  match '/users/:user_id/subscribe', to: 'subscriptions#create', as: 'user_subscribe', via: [:get, :post]

  match '/users/:user_id/unsubscribe', to: 'subscriptions#destroy', as: 'user_unsubscribe', via: [:get, :post]

  match '/users/:user_id/subscription_plans', to: 'subscription_plans#index', as: 'user_subscription_plans', via: [:get, :post]

  resources :users

  match '/deauth/:provider', to: 'users#deauth', via: [:get, :patch, :post]

  get '/dashboard', to: 'users#show', as: 'dashboard'

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match '/logout', to: 'sessions#destroy', via: [:get, :post]

  get '/help', to: 'help#index', as: 'help'
  get '/help/faq', to: 'help#faq', as: 'help_faq'
  get '/help/examples', to: 'help#examples', as: 'help_examples'
  get '/help/contact', to: 'help#contact', as: 'help_contact'

  get '/about', to: 'about#index', as: 'about'
  get '/about/features', to: 'about#features', as: 'features'
  get '/about/subscription_plans', to: 'subscription_plans#index', as: 'subscription_plans'

  match '/:facebook_page_id/:giveaway_id/enter', to: 'giveaways#enter', as: 'enter', via: [:get, :patch, :post]

  root to: 'welcome#index'
end

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  - callout type: 'danger', title: "The form contains #{pluralize(object.errors.count, "error")}.", class: 'error-messages' do
    - object.errors.full_messages.each do |msg|
      %p= msg

app/views/shared/_flash.html.haml
#flash_tray
  %ul.messenger.messenger-fixed.messenger-on-bottom.messenger-on-right.messenger-theme-block
    - if flash.any?
      - flash.each do |level, message|
        = render 'shared/flash_message', level: level, message: message

app/views/shared/_flash_message.html.haml
- if message.is_a?(Hash)
  - title = message.with_indifferent_access['title'].try(:titleize)
  - message = message.with_indifferent_access['content']
- else
  - title = "#{level}".try(:titleize)

%li.rails-flash.messenger-message-slot.animated.fadeInUp
  .messenger-message.message{class: "message-#{level} alert-#{level}"}
    .messenger-message-inner
      %span.message-icon
        %i.fa.fa-bell-o.time-icon{class: "bg-#{level}"}
      .message-text
        - unless "#{title}".blank?
          %h4= "#{title}".html_safe
        - unless "#{message}".blank?
          %p= message.html_safe
      %button.messenger-close{type: "button"} ×
    .messenger-spinner
      %span.messenger-spinner-side.messenger-spinner-side-left
        %span.messenger-spinner-fill
      %span.messenger-spinner-side.messenger-spinner-side-right
        %span.messenger-spinner-fill

app/views/shared/_init_breadcrumbs.html.haml
- breadcrumb :root

- if @page
  - breadcrumb :facebook_page, @page

- if @giveaway
  - breadcrumb :giveaway, @giveaway

- if current_action == 'giveaways/active'
  - breadcrumb :active_giveaway, @page

- if current_action == 'giveaways/pending'
  - breadcrumb :pending_giveaways, @page

- if current_action == 'giveaways/completed'
  - breadcrumb :completed_giveaways, @page

- if current_action == 'users/edit'
  - breadcrumb :user, current_user

- if current_action == 'subscription_plans/index'
  - breadcrumb :subscription_plans, current_user

app/views/shared/_init_globals.html.haml
- if @page
  %script{type: 'text/javascript'}
    :plain
      (function() {
        _SG.CurrentPage.ID = '#{@page.id}';
        _SG.Paths.facebookPage = '#{facebook_page_path(@page)}';
        _SG.Paths.giveaways = '#{facebook_page_giveaways_path(@page)}';
        _SG.Paths.checkSchedule = '#{check_schedule_facebook_page_giveaways_path(@page)}';
        _SG.Paths.subscriptionPlans = '#{facebook_page_subscription_plans_path(@page)}';
        _SG.Paths.pageSubscribe = '#{facebook_page_subscribe_path(@page)}';
      }());

  - if @page.has_active_subscription?
    %script{type: 'text/javascript'}
      :plain
        (function() {
          _SG.CurrentPage.isSubscribed = true;
        }());

- if @giveaway
  %script{type: 'text/javascript'}
    :plain
      (function() {
        _SG.CurrentGiveaway.ID = '#{@giveaway.id}';
        _SG.CurrentGiveaway.status = '#{@giveaway.status}';
      }());

  - if @giveaway.persisted?
    %script{type: 'text/javascript'}
      :plain
        (function() {
          _SG.Paths.giveawayEntries = '#{facebook_page_giveaway_entries_path(@giveaway.facebook_page, @giveaway)}';
        }());

- if current_user && current_user.fb_uid
  %script{type: 'text/javascript'}
    :plain
      (function() {
        _SG.CurrentUser.name = '#{current_user.name}';
        _SG.CurrentUser.FB_UID = '#{current_user.fb_uid}';
        _SG.CurrentUser.email = '#{current_user.email}';
        _SG.Paths.userPages = '#{facebook_pages_path}';
        _SG.Paths.userSubscribe = '#{user_subscribe_path(current_user)}';
        _SG.CurrentUser.justSubscribed = '#{session.delete(:just_subscribed)}';
      }());

- if session[:proposed_end_date]
  %script{type: 'text/javascript'}
    :plain
      (function() {
        _SG.CurrentGiveaway.proposedEndDate = '#{session[:proposed_end_date]}';
      }());

- if session[:proposed_tab_name]
  %script{type: 'text/javascript'}
    :plain
      (function() {
        _SG.CurrentGiveaway.proposedTabName = '#{session[:proposed_tab_name]}';
      }());

%script{type: 'text/javascript'}
  :plain
    (function() {
      deepFreeze(_SG);
    }());