config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  require 'sidekiq/web'

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  match '/widgets', to: 'widgets#index', via: [:get]

  match '/terms', to: 'welcome#terms', via: [:get]
  match '/privacy', to: 'welcome#privacy', via: [:get]
  match '/support', to: 'welcome#support', via: [:get]

  match '/canvas', to: 'canvas#index', via: [:get, :patch, :post]
  match '/canvas/edit', to: 'canvas#edit', via: [:get, :patch, :post]
  match '/giveaways/tab', to: 'giveaways#tab', via: [:get, :patch, :post]

  resources :likes, only: [:create]

  resources :facebook_pages, only: [:index, :show] do

    resources :giveaways do
      resources :entries, only: [:index, :create, :update]

      get :export_entries, on: :member
      get :active, on: :collection
      get :pending, on: :collection
      get :completed, on: :collection
      get :check_schedule, on: :collection
      get :clone, on: :member
      match :start, on: :member, via: [:get, :patch, :post]
      get :start_modal, on: :member
      get :end, on: :member
    end
  end

  match '/facebook_pages/:facebook_page_id/subscribe', to: 'subscriptions#create', as: 'facebook_page_subscribe', via: [:get, :post]

  match '/facebook_pages/:facebook_page_id/subscription_plans', to: 'subscription_plans#index', as: 'facebook_page_subscription_plans', via: [:get, :post]

  match '/users/:user_id/subscribe', to: 'subscriptions#create', as: 'user_subscribe', via: [:get, :post]

  match '/users/:user_id/unsubscribe', to: 'subscriptions#destroy', as: 'user_unsubscribe', via: [:get, :post]

  match '/users/:user_id/subscription_plans', to: 'subscription_plans#index', as: 'user_subscription_plans', via: [:get, :post]

  resources :users

  match '/deauth/:provider', to: 'users#deauth', via: [:get, :patch, :post]

  get '/dashboard', to: 'users#show', as: 'dashboard'

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match '/logout', to: 'sessions#destroy', via: [:get, :post]

  get '/help', to: 'help#index', as: 'help'
  get '/help/faq', to: 'help#faq', as: 'help_faq'
  get '/help/examples', to: 'help#examples', as: 'help_examples'
  get '/help/contact', to: 'help#contact', as: 'help_contact'

  get '/about', to: 'about#index', as: 'about'
  get '/about/features', to: 'about#features', as: 'features'
  get '/about/subscription_plans', to: 'subscription_plans#index', as: 'subscription_plans'

  match '/:facebook_page_id/:giveaway_id/enter', to: 'giveaways#enter', as: 'enter', via: [:get, :patch, :post]

  root to: 'welcome#index'
end

app/views/layouts/navigation/sidebar/_about.html.haml
- within_section = body_class.match(/about-index|subscription_plans-index/)

- if within_section

  %li{class: "#{within_section ? 'active' : ''}"}
    %a{href: "#about"}
      %i.fa.fa-users.icon
        %b.bg-success
      %span.pull-right
        %i.fa.fa-angle-down.text
        %i.fa.fa-angle-up.text-active
      %span About Us
    %ul.nav.lt
      = active_link_to about_path, active: :exclusive, wrap_tag: :li do
        %i.fa.fa-angle-right
        %span Features
      = active_link_to subscription_plans_path, wrap_tag: :li do
        %i.fa.fa-angle-right
        %span Plans &amp; Pricing

- else

  %li{class: "#{within_section ? 'active' : ''}"}
    = link_to about_path do
      %i.fa.fa-users.icon
        %b.bg-success
      %span.pull-right
        %i.fa.fa-angle-down.text
        %i.fa.fa-angle-up.text-active
      %span About Us

app/views/layouts/navigation/sidebar/_account.html.haml
%li{class: "#{body_class.match(/users-edit|subscription_plans-index/) ? 'active' : ''}"}
  %a{href: "#account"}
    %i.fa.fa-user.icon
      %b.bg-primary
    %span.pull-right
      %i.fa.fa-angle-down.text
      %i.fa.fa-angle-up.text-active
    %span Account
  %ul.nav.lt
    = active_link_to edit_user_path(current_user), wrap_tag: :li do
      %i.fa.fa-angle-right
      %span Basic Info
    = active_link_to user_subscription_plans_path(current_user), wrap_tag: :li do
      %i.fa.fa-angle-right
      %span Subscription

app/views/layouts/navigation/sidebar/_dashboard.html.haml
= active_link_to dashboard_path, wrap_tag: :li do
  %i.fa.fa-dashboard.icon
    %b.bg-danger
  %span.hidden-nav-xs Dashboard
  %span.hidden-nav Home

app/views/layouts/navigation/sidebar/_facebook_pages.html.haml
- activate = defined?(active) ? active : %w(facebook_pages giveaways).include?(controller.controller_name)

%li#facebook_pages_nav{class: activate ? 'active' : ''}
  %a{href: "#pages", class: activate ? 'active' : ''}
    %i.fa.fa-facebook-square.icon
      %b.bg-info
    %span.pull-right
      %i.fa.fa-angle-down.text
      %i.fa.fa-angle-up.text-active
    %span Pages
  %ul.nav.lt.pages
    - current_user.facebook_pages.each do |page|
      - if page == @page
        %li.active
          %a.active{href: "##{page.slug}"}
            %i.fa.fa-angle-down.text
            %i.fa.fa-angle-up.text-active
            %span= page.name
          %ul.nav.bg
            = active_link_to active_facebook_page_giveaways_path(page), wrap_tag: :li do
              %i.fa.fa-bolt
              %span Active Giveaway
            = active_link_to pending_facebook_page_giveaways_path(page), wrap_tag: :li do
              %i.fa.fa-clock-o
              %span Pending Giveaways
            = active_link_to completed_facebook_page_giveaways_path(page), wrap_tag: :li do
              %i.fa.fa-archive
              %span Completed Giveaways
            = active_link_to new_facebook_page_giveaway_path(page), wrap_tag: :li do
              %i.fa.fa-plus
              %span New Giveaway
      - else
        = active_link_to facebook_page_path(page), wrap_tag: :li do
          %i.fa.fa-angle-right
          %span= page.name

app/views/layouts/navigation/sidebar/_help.html.haml
%li{class: "#{body_class.match(/help-index|help-faq|help-examples|help-contact/) ? 'active' : ''}"}
  %a{href: "#help"}
    %i.fa.fa-question-circle.icon
      %b.bg-warning
    %span.pull-right
      %i.fa.fa-angle-down.text
      %i.fa.fa-angle-up.text-active
    %span Help
  %ul.nav.lt
    = active_link_to help_faq_path, wrap_tag: :li do
      %i.fa.fa-angle-right
      %span FAQ
    = active_link_to help_examples_path, wrap_tag: :li do
      %i.fa.fa-angle-right
      %span Examples
    = active_link_to help_contact_path, wrap_tag: :li do
      %i.fa.fa-angle-right
      %span Contact