config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  require 'sidekiq/web'

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  match '/widgets', to: 'widgets#index', via: [:get]

  match '/terms', to: 'welcome#terms', via: [:get]
  match '/privacy', to: 'welcome#privacy', via: [:get]
  match '/support', to: 'welcome#support', via: [:get]

  match '/canvas', to: 'canvas#index', via: [:get, :patch, :post]
  match '/canvas/edit', to: 'canvas#edit', via: [:get, :patch, :post]
  match '/giveaways/tab', to: 'giveaways#tab', via: [:get, :patch, :post]

  resources :likes, only: [:create]

  resources :facebook_pages, only: [:index, :show] do

    resources :giveaways do
      resources :entries, only: [:index, :create, :update]

      get :export_entries, on: :member
      get :active, on: :collection
      get :pending, on: :collection
      get :completed, on: :collection
      get :check_schedule, on: :collection
      get :clone, on: :member
      match :start, on: :member, via: [:get, :patch, :post]
      get :start_modal, on: :member
      get :end, on: :member
    end
  end

  match '/facebook_pages/:facebook_page_id/subscribe', to: 'subscriptions#create', as: 'facebook_page_subscribe', via: [:get, :post]

  match '/facebook_pages/:facebook_page_id/subscription_plans', to: 'subscription_plans#index', as: 'facebook_page_subscription_plans', via: [:get, :post]

  match '/users/:user_id/subscribe', to: 'subscriptions#create', as: 'user_subscribe', via: [:get, :post]

  match '/users/:user_id/unsubscribe', to: 'subscriptions#destroy', as: 'user_unsubscribe', via: [:get, :post]

  match '/users/:user_id/subscription_plans', to: 'subscription_plans#index', as: 'user_subscription_plans', via: [:get, :post]

  resources :users

  match '/deauth/:provider', to: 'users#deauth', via: [:get, :patch, :post]

  get '/dashboard', to: 'users#show', as: 'dashboard'

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match '/logout', to: 'sessions#destroy', via: [:get, :post]

  get '/help', to: 'help#index', as: 'help'
  get '/help/faq', to: 'help#faq', as: 'help_faq'
  get '/help/examples', to: 'help#examples', as: 'help_examples'
  get '/help/contact', to: 'help#contact', as: 'help_contact'

  get '/about', to: 'about#index', as: 'about'
  get '/about/features', to: 'about#features', as: 'features'
  get '/about/subscription_plans', to: 'subscription_plans#index', as: 'subscription_plans'

  match '/:facebook_page_id/:giveaway_id/enter', to: 'giveaways#enter', as: 'enter', via: [:get, :patch, :post]

  root to: 'welcome#index'
end

app/helpers/giveaways_helper.rb
require 'dotiw'

module GiveawaysHelper

  include PublicUtils

  include ActionView::Helpers::DateHelper

  def time_from_now(time, options = {})
    only_options = if options[:only]
      options[:only]
    elsif (1.seconds.ago..1.minute.from_now).cover? time
      %w(seconds)
    elsif (1.minute.from_now..24.hours.from_now).cover? time
      %w(hours minutes)
    elsif time > 1.month.from_now
      %w(months days)
    elsif time > 1.year.from_now
      %w(years months)
    elsif (1.minute.ago..2.seconds.ago).cover? time
      %w(seconds)
    elsif (24.hours.ago..1.minute.ago).cover? time
      %w(hours minutes)
    elsif (1.month.ago..24.hours.ago).cover? time
      %w(days)
    elsif (1.year.ago..1.month.ago).cover? time
      %w(months days)
    elsif time < 1.year.ago
      %w(years months)
    else
      %w(days hours)
    end

    accumulate_options = only_options.first.to_sym rescue :days

    distance_of_time_in_words(Time.now, time, include_seconds: false, only: only_options, accumulate_on: accumulate_options)
  end

  def giveaway_header_class(giveaway)
    case giveaway.status
      when 'Active'
        'bg-primary'
      when 'Pending'
        'bg-dark'
      when 'Completed'
        'bg-danger'
    end
  end

  def status_label(giveaway)
    case giveaway.status
      when 'Active'
        active_status_label(giveaway)
      when 'Pending'
        pending_status_label(giveaway)
      when 'Completed'
        completed_status_label(giveaway)
    end
  end

  def active_status_label(giveaway)
    label = <<-eos
      <div class="ui ribbon label teal">
        <strong>Active</strong><br />
        Started on #{datetime_mdy(giveaway.start_date)}<br />
        Ends on #{datetime_mdy(giveaway.end_date)}
      </div>
    eos
    label.html_safe
  end

  def pending_status_label(giveaway)
    label = <<-eos
      <div class="ui ribbon label">
        <strong>Pending</strong><br />
    eos
    if giveaway.start_date
      label += <<-eos
        Starts on #{datetime_mdy(giveaway.start_date)}
      eos
    end
    if giveaway.end_date
      label += <<-eos
        <br />
        Ends on #{datetime_mdy(giveaway.end_date)}
      eos
    end
    label += "</div>"
    label.html_safe
  end

  def completed_status_label(giveaway)
    label = <<-eos
      <div class="ui ribbon label red">
        <strong>Completed</strong><br />
        Started on #{datetime_mdy(giveaway.start_date)}<br />
        Ended on #{datetime_mdy(giveaway.end_date)}
      </div>
    eos
    label.html_safe
  end

  def boolean_label(boolean)
    if to_bool(boolean)
      '<span class=\'label bg-primary\'>TRUE</span>'.html_safe
    else
      '<span class=\'label bg-danger\'>FALSE</span>'.html_safe
    end
  end

  def start_date_label(giveaway, options = {})
    return "No Start Date" unless giveaway.start_date

    start_date = if options[:blank]
      nil
    elsif options[:relative]
      ts = "#{time_from_now(giveaway.start_date)}"
      giveaway.start_date.past? ? (ts += " ago") : ts
    else
      giveaway.start_date
    end

    return start_date if giveaway.active? || giveaway.completed?
    if giveaway.cannot_schedule?
      "<span class=\"giveaway-start-date-warning\" data-container=\"#start_date_popover_container\" data-toggle=\"popover\" data-placement=\"auto top\" data-html=\"true\" data-title=\"Inactive Start Date\" data-content=\"<p>A Pro subscription is required in order to schedule a giveaway.</p><a class='btn btn-primary btn-block' href='#{facebook_page_subscription_plans_path(giveaway.facebook_page)}'>Choose a Plan</a>\"><s>#{start_date}</s></span>".html_safe
    elsif giveaway.has_start_date_conflict?
      "<span class=\"giveaway-start-date-warning\" data-container=\"#start_date_popover_container\" data-toggle=\"popover\" data-placement=\"auto top\" data-html=\"true\" data-title=\"Inactive Start Date\" data-content=\"<p>#{giveaway_date_link(giveaway)}</p><p>This giveaway has scheduling conflicts with the following giveaways:</p><p>#{conflicts(giveaway)}</p><p>Please update your giveaway schedules in order to activate this start date.</p><a class='btn btn-default btn-block' href='#{edit_facebook_page_giveaway_path(giveaway.facebook_page, giveaway)}'><i class='fa fa-pencil'></i>&nbsp;&nbsp;Edit Giveaway</a>\"><s>#{start_date}</s></span>".html_safe
    else
      start_date
    end
  end

  def end_date_label(giveaway, options = {})
    return "No End Date" unless giveaway.end_date

    end_date = if options[:blank]
      nil
    elsif options[:relative]
      ts = "#{time_from_now(giveaway.end_date)}"
      giveaway.end_date.past? ? (ts += " ago") : ts
    else
      giveaway.end_date
    end

    return end_date if giveaway.completed?
    if giveaway.cannot_schedule?
      "<span class='giveaway-end-date-warning' data-toggle='popover' data-placement='auto top' data-html='true' data-title='Inactive End Date' data-content='<p>A Pro subscription is required in order to schedule a giveaway.</p><a class=\"btn btn-primary btn-block\" href=\"#{facebook_page_subscription_plans_path(giveaway.facebook_page)}\">Choose a Plan</a>'><s>#{end_date}</s></span>".html_safe
    else
      end_date
    end
  end

  def conflicts(giveaway)
    giveaway.start_date_conflicts.map do |g|
      giveaway_date_link(g)
    end.join('<br />')
  end

  def giveaway_date_link(giveaway)
    "<a href='#{facebook_page_giveaway_path(giveaway.facebook_page, giveaway)}'>#{giveaway.title}</a><br />#{giveaway.start_date.to_formatted_s(:simple_date)} - #{giveaway.end_date.to_formatted_s(:simple_date)}"
  end
end

app/views/giveaways/_actions.html.haml
- if giveaway.active?

  = render 'giveaways/actions/active', giveaway: giveaway

- elsif giveaway.pending?

  = render 'giveaways/actions/pending', giveaway: giveaway

- elsif giveaway.completed?

  = render 'giveaways/actions/completed', giveaway: giveaway

app/views/giveaways/_active.html.haml
%section#active_giveaway_tabs
  %header.panel-heading.text-right.bg-light.clearfix
    %ul.nav.nav-tabs.pull-left
      %li.active
        %a#overview_tab_trigger{"data-toggle" => "tab", href: "#overview_tab"}
          <i class='fa fa-dashboard text-default m-r-xs'></i>Overview
      %li
        = link_to "<i class='fa fa-users text-default m-r-xs'></i>Entries".html_safe, facebook_page_giveaway_entries_path(page, giveaway), remote: true, 'data-toggle' => 'tab', 'data-target' => '#entries_tab', id: 'entries_tab_trigger'
      %li
        = link_to "<i class='fa fa-file-text-o text-default m-r-xs'></i>Details".html_safe, facebook_page_giveaway_path(page, giveaway), remote: true, 'data-toggle' => 'tab', 'data-target' => '#details_tab', id: 'details_tab_trigger'
      = render 'giveaways/active/actions_dropdown', giveaway: giveaway
  .panel-body
    .tab-content
      = render 'giveaways/active/actions_button', giveaway: giveaway
      #overview_tab.tab-pane.fade.active.in
        = render 'giveaways/active/stats', giveaway: giveaway
        = render 'giveaways/active/graphs', giveaway: giveaway, page: page, flot: flot if giveaway.canhaz_advanced_analytics?
      #entries_tab.tab-pane.fade
        .text-center.progress-wrapper
          .sg-progress-block
            .bar
      #details_tab.tab-pane.fade
        .text-center.progress-wrapper
          .sg-progress-block
            .bar

app/views/giveaways/_completed.html.haml
%section#active_giveaway_tabs.completed-giveaway-tabs
  %header.panel-heading.text-right.bg-light.clearfix
    %ul.nav.nav-tabs.pull-left
      %li.active
        %a#overview_tab_trigger{"data-toggle" => "tab", href: "#overview_tab"}
          %i.fa.fa-dashboard.text-default.m-r-xs
          Overview
      %li
        = link_to "<i class='fa fa-users text-default m-r-xs'></i>Entries".html_safe, facebook_page_giveaway_entries_path(page, giveaway), remote: true, 'data-toggle' => 'tab', 'data-target' => '#entries_tab', id: 'entries_tab_trigger'
      %li
        = link_to "<i class='fa fa-cogs text-default m-r-xs'></i>Details".html_safe, facebook_page_giveaway_path(page, giveaway), remote: true, 'data-toggle' => 'tab', 'data-target' => '#details_tab', id: 'details_tab_trigger'

  .panel-body
    .tab-content
      #overview_tab.tab-pane.fade.active.in
        = render 'giveaways/active/stats', giveaway: giveaway
        = render 'giveaways/active/graphs', giveaway: giveaway, page: page, flot: flot if giveaway.canhaz_advanced_analytics?
      #entries_tab.tab-pane.fade
        .text-center.progress-wrapper
          .sg-progress-block
            .bar
      #details_tab.tab-pane.fade
        .text-center.progress-wrapper
          .sg-progress-block
            .bar

app/views/giveaways/_form.html.haml
#form-wizard.wizard.clearfix
  %ul.steps
    %li.active{"data-target" => "#step1"}<
      %span.badge.badge-info> 1
      Basic Info
    %li{"data-target" => "#step2"}<
      %span.badge> 2
      Schedule
    %li{"data-target" => "#step3"}<
      %span.badge> 3
      Images
    %li{"data-target" => "#step4"}<
      %span.badge> 4
      Terms
    %li{"data-target" => "#step5"}<
      %span.badge> 5
      Options
  .actions
    %button.btn.btn-default.btn-xs.btn-prev{"data-target" => "#form-wizard", "data-wizard" => "previous", disabled: "disabled", type: "button"} Prev
    %button.btn.btn-default.btn-xs.btn-next{"data-last" => "Finish", "data-target" => "#form-wizard", "data-wizard" => "next", type: "button"} Next
.step-content
  = simple_form_for [page, giveaway], html: { class: 'giveaway-form fluid', multipart: true, novalidate: true } do |f|
    = render 'shared/error_messages', object: f.object
    #step1.step-pane.active.basic-info
      = render "giveaways/form/basic_info", f: f
    #step2.step-pane.schedule
      = render "giveaways/form/schedule", f: f
    #step3.step-pane.images
      = render "giveaways/form/images", f: f
    #step4.step-pane.terms
      = render "giveaways/form/terms", f: f
    #step5.step-pane.preferences
      = render "giveaways/form/preferences", f: f
  .actions.m-t.btn-group.btn-group-relaxed
    %button.btn.btn-default.btn-lg.btn-left.btn-prev{"data-target" => "#form-wizard", "data-wizard" => "previous", disabled: "disabled", type: "button"} Previous
    %button.btn.btn-primary.btn-lg.btn-right.btn-next{"data-last" => "Finish", "data-target" => "#form-wizard", "data-wizard" => "next", type: "button"} Next

    -# - unless giveaway.active? || giveaway.new_record?
    -#   .ui.right.floated.tiny.red.buttons
    -#     = link_to 'Delete', facebook_page_giveaway_path(page, giveaway), method: :delete, 'data-confirm' => "Are you sure you want to delete the giveaway? You will not be able to recover this giveaway if you proceed.", class: 'ui button'

app/views/giveaways/_init_tab_globals.html.haml
:javascript
  (function() {
    function deepFreeze (o) {
      var prop, propKey;
      Object.freeze(o);
      for (propKey in o) {
        prop = o[propKey];
        if (!o.hasOwnProperty(propKey) || !(typeof prop === "object") || Object.isFrozen(prop)) {
          continue;
        }
        deepFreeze(prop);
      }
    }

    _SG = {
      Config: {
        FB_APP_ID: '#{FB_APP_ID}',
        SG_SSL_DOMAIN: '#{SG_SSL_DOMAIN}'
      },
      CurrentGiveaway: #{giveaway_hash.to_json},
      Paths: {
        likes: '#{likes_path}',
        giveawayEntry: '#{facebook_page_giveaway_entries_path(giveaway_hash.current_page, giveaway_hash.giveaway.id)}'
      }
    }

    deepFreeze(_SG);
  }());

app/views/giveaways/_list_item.html.haml
- if giveaway.status == "Active"

  %header.active
    .image= image_tag(giveaway.feed_image.feed.url)
    %h1= truncate(giveaway.title, length: 26)
    %p is #{giveaway.status}

- elsif giveaway.status == "Pending"

  %header.giveaway_preview
    .image
      = image_tag(giveaway.feed_image.feed.url)
    .title
      %h1= link_to truncate(giveaway.title, length: 26), facebook_page_giveaway_path(page, giveaway)
      %h2
        %span.gray Prize
        = giveaway.prize
    .buttons
      = link_to "<i class='icon-edit'></i> Edit".html_safe, facebook_page_giveaway_path(page, giveaway), class: "btn btn-large btn-edit"

      = render 'publish_button', giveaway: giveaway, page: page

- elsif giveaway.status == "Completed"

  %tr
    %td= image_tag(giveaway.feed_image.thumb.url)
    %td= link_to truncate(giveaway.title, length: 26), facebook_page_giveaway_path(page, giveaway)
    %td= giveaway.end_date.strftime('%m/%d/%Y %l:%M %p')
    %td= giveaway.entries.count
    %td= giveaway.impressionist_count
    %td= giveaway.page_likes_while_active

app/views/giveaways/_preview.html.haml
%li.list-group-item.giveaway.preview.animated.fadeInUp
  .row.no-gutter
    .col-xs-12.col-sm-7
      .media
        - avatar link: facebook_page_giveaway_path(giveaway.facebook_page, giveaway), image_url: giveaway.image.preview.url
        .media-body.m-t-sm.m-b-xs
          .h4.media-heading= link_to giveaway.title, facebook_page_giveaway_path(giveaway.facebook_page, giveaway)
          .meta
            - if giveaway.pending?
              %p
                %i.fa.fa-clock-o.m-r-xs
                = start_date_label(giveaway, relative: true)
            - elsif giveaway.completed?
              %p
                %i.fa.fa-clock-o.m-r-xs
                = end_date_label(giveaway, relative: true)
    .col-xs-12.col-sm-5
      .row.m-t-sm-sm.m-b-xs
        - if giveaway.completed?
          = render 'giveaways/preview/stats', giveaway: giveaway
        - if giveaway.pending?
          .avatar-push.text-right-sm.m-r-md-sm.m-l-md-xs
            = render 'giveaways/navigation/primary', giveaway: giveaway, size_class: 'btn-sm'

app/views/giveaways/active.html.haml
- if @giveaway && @giveaway.active?

  = render @giveaway, page: @page, flot: @flot, entries: @entries

- else

  - content_for :page_heading do
    = render 'facebook_pages/header', content: ''

  .panel.panel-default
    .panel-heading
      %h3.panel-title Active Giveaway

    .panel-body.panel-body-callout.text-center-xs

      - callout type: 'info', title: "There is no active giveaway on your page right now." do
        - if @page.giveaways.pending.any?
          %p Create a new giveaway to publish later or publish one of your pending giveaways.
        - else
          %p Create a new giveaway to publish later.

        = link_to '<i class="fa fa-plus m-r-xs"></i>New Giveaway'.html_safe, new_facebook_page_giveaway_path(@page), class: 'btn btn-primary m-t-sm-xs'
        - if @page.giveaways.pending.any?
          = link_to '<i class="fa fa-clock-o m-r-xs"></i>Pending Giveaways'.html_safe, pending_facebook_page_giveaways_path(@page), class: 'btn btn-default m-t-sm-xs'

app/views/giveaways/completed.html.haml
- content_for :page_heading do
  = render 'facebook_pages/header'

.panel.panel-default
  .panel-heading
    %h3.panel-title Completed Giveaways

  - if @giveaways.any?

    = render 'facebook_pages/giveaways', giveaways: @giveaways

    .panel-footer.paging-footer.text-center
      = will_paginate @giveaways, renderer: BootstrapPagination::Rails
      .text-center.paging-info
        = pagination_info @giveaways, model: "#{'giveaway'.pluralize(@giveaways.size)}"

  - else

    .panel-body.panel-body-callout.text-center-xs

      - callout type: 'info', title: "There are no completed giveaways yet." do
        - if @page.giveaways.pending.any?
          %p Create a new giveaway to publish later or publish one of your pending giveaways.
        - else
          %p Create a new giveaway to publish later.

        = link_to '<i class="fa fa-plus m-r-xs"></i>New Giveaway'.html_safe, new_facebook_page_giveaway_path(@page), class: 'btn btn-primary m-t-sm-xs'
        - if @page.giveaways.pending.any?
          = link_to '<i class="fa fa-clock-o m-r-xs"></i>Pending Giveaways'.html_safe, pending_facebook_page_giveaways_path(@page), class: 'btn btn-default m-t-sm-xs'

app/views/giveaways/edit.html.haml
- content_for :page_heading do
  = render 'facebook_pages/header'

.panel.panel-default.wizard-container
  .panel-heading
    %h4.panel-title Edit Giveaway
  = render 'form', page: @page, giveaway: @giveaway

app/views/giveaways/enter.html.haml
#gk_giveaway.gk-version-b
  .giveaway-widget
    .giveaway-image
      .inset-shadow
      = image_tag @giveaway.image.tab.url
    .giveaway-meta
      %h1.giveaway-title
        = @giveaway.title
      %h2.giveaway-prize
        = "Win #{@giveaway.prize}"
    .giveaway-description
      .pull-left.avatar-wrapper
        %span.thumb.masked.avatar{:style => "background-image: url(#{@giveaway.facebook_page.avatar_large})"}
      %h3.description-text
        = @giveaway.description_text
    .giveaway-actions
      %button#enter_giveaway.ladda-button{"data-style" => "zoom-in", "data-spinner-size" => "65"}
        %span.ladda-label Enter Now
  .giveaway-terms
    - unless @giveaway.facebook_page.canhaz_white_label?
      %p.powered-by Powered by <a href='http://giveawaykit.com' target='_blank'>Giveaway Kit</a>
    %p This promotion is in no way sponsored, endorsed or administered by, or associated with, Facebook. You understand that you are providing your information to "#{@giveaway.facebook_page.name}" and not to Facebook. Your information will only be used to administer this promotion. Entry in this promotion is subject to the #{@giveaway.terms_link}.
    .terms-text.hidden{style: "display:none"}= @giveaway.terms_text

app/views/giveaways/index.html.haml
= render @giveaways

app/views/giveaways/new.html.haml
- content_for :page_heading do
  = render 'facebook_pages/header'

.panel.panel-default.wizard-container
  .panel-heading
    %h4.panel-title New Giveaway
  = render 'form', page: @page, giveaway: @giveaway

app/views/giveaways/pending.html.haml
- content_for :page_heading do
  = render 'facebook_pages/header'

.panel.panel-default
  .panel-heading
    %h3.panel-title Pending Giveaways

  - if @page.giveaways.pending.any?

    - if @page.giveaways.active.any?

      .panel-body.panel-body-callout

        - callout type: 'info', title: "There is an active giveaway on your page right now." do
          %p You can publish a pending giveaway once your active giveaway has ended.

    - else

      .panel-body.panel-body-callout

        - callout type: 'info', title: "There is no active giveaway on your page right now." do
          %p Go ahead and publish one.

    #start_date_popover_container.popover-container
    = render 'facebook_pages/giveaways', giveaways: @giveaways

    .panel-footer.paging-footer.text-center
      = will_paginate @giveaways, renderer: BootstrapPagination::Rails
      .text-center.paging-info
        = pagination_info @giveaways, model: "#{'giveaway'.pluralize(@giveaways.size)}"

    = render 'giveaways/pending/start_modal_wrapper'

  - else

    .panel-body.panel-body-callout.text-center-xs

      - callout type: 'info', title: "There are no pending giveaways." do
        %p Create a new giveaway to publish later.
        = link_to '<i class="fa fa-plus m-r-xs"></i>New Giveaway'.html_safe, new_facebook_page_giveaway_path(@page), class: 'btn btn-primary m-t-sm-xs'