config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  require 'sidekiq/web'

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  match '/widgets', to: 'widgets#index', via: [:get]

  match '/terms', to: 'welcome#terms', via: [:get]
  match '/privacy', to: 'welcome#privacy', via: [:get]
  match '/support', to: 'welcome#support', via: [:get]

  match '/canvas', to: 'canvas#index', via: [:get, :patch, :post]
  match '/canvas/edit', to: 'canvas#edit', via: [:get, :patch, :post]
  match '/giveaways/tab', to: 'giveaways#tab', via: [:get, :patch, :post]

  resources :likes, only: [:create]

  resources :facebook_pages, only: [:index, :show] do

    resources :giveaways do
      resources :entries, only: [:index, :create, :update]

      get :export_entries, on: :member
      get :active, on: :collection
      get :pending, on: :collection
      get :completed, on: :collection
      get :check_schedule, on: :collection
      get :clone, on: :member
      match :start, on: :member, via: [:get, :patch, :post]
      get :start_modal, on: :member
      get :end, on: :member
    end
  end

  match '/facebook_pages/:facebook_page_id/subscribe', to: 'subscriptions#create', as: 'facebook_page_subscribe', via: [:get, :post]

  match '/facebook_pages/:facebook_page_id/subscription_plans', to: 'subscription_plans#index', as: 'facebook_page_subscription_plans', via: [:get, :post]

  match '/users/:user_id/subscribe', to: 'subscriptions#create', as: 'user_subscribe', via: [:get, :post]

  match '/users/:user_id/unsubscribe', to: 'subscriptions#destroy', as: 'user_unsubscribe', via: [:get, :post]

  match '/users/:user_id/subscription_plans', to: 'subscription_plans#index', as: 'user_subscription_plans', via: [:get, :post]

  resources :users

  match '/deauth/:provider', to: 'users#deauth', via: [:get, :patch, :post]

  get '/dashboard', to: 'users#show', as: 'dashboard'

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match '/logout', to: 'sessions#destroy', via: [:get, :post]

  get '/help', to: 'help#index', as: 'help'
  get '/help/faq', to: 'help#faq', as: 'help_faq'
  get '/help/examples', to: 'help#examples', as: 'help_examples'
  get '/help/contact', to: 'help#contact', as: 'help_contact'

  get '/about', to: 'about#index', as: 'about'
  get '/about/features', to: 'about#features', as: 'features'
  get '/about/subscription_plans', to: 'subscription_plans#index', as: 'subscription_plans'

  match '/:facebook_page_id/:giveaway_id/enter', to: 'giveaways#enter', as: 'enter', via: [:get, :patch, :post]

  root to: 'welcome#index'
end

app/views/layouts/navigation/_breadcrumbs.html.haml
%ul.breadcrumb.no-border.no-radius.b-b.b-light.pull-in
  - breadcrumbs(display_single_fragment: true).tap do |links|
    - links.each do |link|
      %li
        - if link.current?
          = link.text
        - else
          = link_to link.text, link.url

app/views/layouts/navigation/_header.html.haml
- if content_for?(:page_subheading) || content_for?(:page_heading)
  .m-b-md.layouts-header

    %h3.m-b-none= yield :page_heading

    - if content_for? :page_subheading
      %small= yield :page_subheading

app/views/layouts/navigation/_my_account.html.haml
%ul.nav.navbar-nav.navbar-right.m-n.hidden-xs.nav-user
  %li.hidden-xs
    %a.dropdown-toggle.dker{"data-toggle" => "dropdown", href: "#"}
      %i.fa.fa-bell
      %span.badge.badge-sm.up.bg-danger.m-l-n-sm.count 2
    %section.dropdown-menu.aside-xl
      %section.panel.bg-white
        %header.panel-heading.b-light.bg-light
          %strong
            You have
            %span.count 2
            notifications
        .list-group.list-group-alt.animated.fadeInRight
          %a.media.list-group-item{href: "#"}
            %span.pull-left.thumb-sm
              = image_tag 'avatar_default.jpg', class: 'img-circle', alt: 'Jon said'
            %span.media-body.block.m-b-none
              Use awesome animate.css
              %br/
              %small.text-muted 10 minutes ago
          %a.media.list-group-item{href: "#"}
            %span.media-body.block.m-b-none
              1.0 initial released
              %br/
              %small.text-muted 1 hour ago
        %footer.panel-footer.text-sm
          %a.pull-right{href: "#"}
            %i.fa.fa-cog
          %a{"data-toggle" => "class:show animated fadeInRight", href: "#notes"} See all the notifications
  %li.dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
      - unlinked_avatar(class: 'pull-left', size: 32, image_url: current_user.avatar)
      = current_user.name
      %b.caret
    %ul.dropdown-menu.animated.fadeInRight
      %span.arrow.top
      = active_link_to 'Account', edit_user_path(current_user), wrap_tag: :li
      = active_link_to 'Help', help_path, wrap_tag: :li
      %li.divider
      %li= link_to 'Logout', logout_path

app/views/layouts/navigation/_my_pages.html.haml
%ul#my_pages_dropdown.nav.navbar-nav.hidden-xs
  %li.dropdown
    %a.dropdown-toggle.dker{"data-toggle" => "dropdown", href: "#"}
      %i.fa.fa-facebook-square
      %span.font-bold My Pages
    %section#facebook_pages_list.panel.panel-default.dropdown-menu.aside-xl.on.animated.fadeInLeft.no-borders
      %header.panel-heading
        %input.search.form-control{placeholder: "Search", type: "text"}
      %ul.list-group.bg-white.no-radius.alt
        - current_user.facebook_pages.each do |page|
          %li
            = active_link_to facebook_page_path(page), class: 'list-group-item media' do
              %span.pull-left.thumb-sm
                %img.img-circle{alt: page.name, src: page.avatar_square}
              .pull-right.text-success.m-t-sm
                %i.fa.fa-circle
              .media-body
                %div.name= page.name
                %small= like_count_label(page)

app/views/layouts/navigation/_primary.html.haml
= render 'layouts/navigation/my_pages' if signed_in?
= render 'layouts/navigation/my_account' if signed_in?

app/views/layouts/navigation/_sidebar.html.haml
%section.w-f.scrollable
  .slim-scroll{"data-color" => "#333333", "data-disable-fade-out" => "true", "data-distance" => "0", "data-height" => "auto", "data-size" => "5px"}
    %nav.nav-primary.hidden-xs
      %ul.nav
        - if signed_in?
          = render 'layouts/navigation/sidebar/dashboard'
          = render 'layouts/navigation/sidebar/facebook_pages'
          = render 'layouts/navigation/sidebar/account'
        - else
          = render 'layouts/navigation/sidebar/about'
        = render 'layouts/navigation/sidebar/help'